version: "3.7"
services:
  vlmcsd:
    build:
      context: ./
      dockerfile: Dockerfile
    image: lianshufeng/kms
    ports:
      - "1688:1688"
    restart: always

  tomcat_kms:
    image: lianshufeng/tomcat
    volumes:
      - "./conf:/opt/tomcat/conf"
      - "./webapps:/opt/tomcat/webapps"
    container_name: tomcat_kms
    restart: always
    networks:
      - custom_net
networks:
  custom_net:
   external:
      name: app_net